services:
  php:
    image: thecodingmachine/php:8.1-v4-cli
    container_name: async-bus_php
    depends_on:
      redis:
        condition: service_started
    environment:
      - PHP_EXTENSION_XDEBUG=1
      - XDEBUG_MODE=debug
    init: true
    networks:
      - async-bus
    restart: "no"
    volumes:
      - ./:/usr/src/app

  redis:
    image: redis:7-alpine
    container_name: async-bus_redis
    networks:
      - async-bus
    restart: "no"

networks:
  async-bus:
    driver: bridge
    name: async-bus
